// Export Functions
function showExportModal() {
    if (courses.length === 0) {
        showNotification('No courses to export', 'error');
        return;
    }
    document.getElementById('exportModal').style.display = 'flex';
}

function closeExportModal() {
    document.getElementById('exportModal').style.display = 'none';
}

function showLoading() {
    document.getElementById('loadingOverlay').style.display = 'flex';
}

function hideLoading() {
    document.getElementById('loadingOverlay').style.display = 'none';
}

// Export as PDF
function exportPDF() {
    showLoading();
    closeExportModal();
    
    html2canvas(document.querySelector('.timetable-container'), {
        scale: 2,
        backgroundColor: '#ffffff',
        useCORS: true,
        onclone: function(clonedDoc) {
            const elementsToHide = clonedDoc.querySelectorAll('.timetable-header button, .cell-selected::after');
            elementsToHide.forEach(el => {
                if (el.style) el.style.display = 'none';
            });
        }
    }).then(canvas => {
        const { jsPDF } = window.jspdf;
        const doc = new jsPDF('landscape', 'mm', 'a4');
        
        doc.setFillColor(0, 51, 102);
        doc.rect(0, 0, 297, 25, 'F');
        doc.setTextColor(255, 255, 255);
        doc.setFontSize(20);
        doc.setFont('helvetica', 'bold');
        doc.text('SMART FFCS TIMETABLE-PLANNER', 148, 15, { align: 'center' });
        
        doc.setFontSize(12);
        doc.setFont('helvetica', 'normal');
        doc.text('VIT BHOPAL STUDENTS', 148, 22, { align: 'center' });
        
        doc.setTextColor(0, 0, 0);
        doc.setFontSize(10);
        doc.text(`Generated: ${new Date().toLocaleDateString()} ${new Date().toLocaleTimeString()}`, 10, 35);
        doc.text(`Total Courses: ${courses.length} | Total Slots: ${courses.reduce((sum, c) => sum + c.slots.length, 0)}`, 10, 40);
        
        const imgData = canvas.toDataURL('image/png');
        const imgWidth = 280;
        const imgHeight = (canvas.height * imgWidth) / canvas.width;
        
        doc.addImage(imgData, 'PNG', 10, 45, imgWidth, imgHeight);
        
        let yPos = imgHeight + 55;
        
        if (yPos > 180) {
            doc.addPage();
            yPos = 20;
        }
        
        doc.setFontSize(14);
        doc.setFont('helvetica', 'bold');
        doc.text('Registered Courses', 10, yPos);
        yPos += 10;
        
        doc.setFontSize(10);
        doc.setFont('helvetica', 'normal');
        
        courses.forEach((course, index) => {
            if (yPos > 190) {
                doc.addPage();
                yPos = 20;
            }
            
            doc.setFont('helvetica', 'bold');
            doc.text(`${index + 1}. ${course.name}`, 10, yPos);
            yPos += 6;
            
            doc.setFont('helvetica', 'normal');
            if (course.code !== 'N/A') {
                doc.text(`Code: ${course.code}`, 15, yPos);
                yPos += 5;
            }
            if (course.faculty !== 'Not specified') {
                doc.text(`Faculty: ${course.faculty}`, 15, yPos);
                yPos += 5;
            }
            doc.text(`Location: ${course.location} | Slots: ${course.slots.join(', ')}`, 15, yPos);
            yPos += 8;
        });
        
        const pageCount = doc.internal.getNumberOfPages();
        for(let i = 1; i <= pageCount; i++) {
            doc.setPage(i);
            doc.setFontSize(8);
            doc.setTextColor(128, 128, 128);
            doc.text(`Page ${i} of ${pageCount}`, 280, 205, { align: 'right' });
            doc.text('Generated by Smart FFCS Timetable Planner', 10, 205);
        }
        
        doc.save(`Timetable_${new Date().toISOString().split('T')[0]}.pdf`);
        hideLoading();
        showNotification('PDF exported successfully!', 'success');
    }).catch(error => {
        hideLoading();
        showNotification('Error generating PDF: ' + error.message, 'error');
    });
}

// Export as Image
function exportImage() {
    showLoading();
    closeExportModal();
    
    html2canvas(document.querySelector('.timetable-container'), {
        scale: 2,
        backgroundColor: '#ffffff',
        useCORS: true,
        onclone: function(clonedDoc) {
            const selectionMarkers = clonedDoc.querySelectorAll('.cell-selected::after');
            selectionMarkers.forEach(marker => {
                if (marker.parentNode) {
                    marker.parentNode.removeChild(marker);
                }
            });
        }
    }).then(canvas => {
        const link = document.createElement('a');
        link.download = `Timetable_${new Date().toISOString().split('T')[0]}.png`;
        link.href = canvas.toDataURL('image/png');
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
        hideLoading();
        showNotification('Image downloaded successfully!', 'success');
    }).catch(error => {
        hideLoading();
        showNotification('Error generating image: ' + error.message, 'error');
    });
}

// Export as JSON
function exportJSON() {
    closeExportModal();
    
    const exportData = {
        title: "Smart FFCS Timetable",
        university: "VIT Bhopal University",
        exportDate: new Date().toISOString(),
        courses: courses.map(course => ({
            name: course.name,
            code: course.code !== 'N/A' ? course.code : undefined,
            faculty: course.faculty !== 'Not specified' ? course.faculty : undefined,
            location: course.location,
            color: course.color,
            slots: course.slots
        })),
        timetable: {},
        summary: {
            totalCourses: courses.length,
            totalSlots: courses.reduce((sum, c) => sum + c.slots.length, 0),
            daysWithClasses: days.filter(day => 
                courses.some(course => 
                    course.slots.some(slot => 
                        timetableSlots[day].includes(slot)
                    )
                )
            ).length
        }
    };

    days.forEach(day => {
        exportData.timetable[day] = {};
        timetableSlots[day].forEach(slotId => {
            const course = courses.find(c => c.slots.includes(slotId));
            if (course) {
                exportData.timetable[day][slotId] = {
                    course: course.name,
                    location: course.location
                };
            }
        });
    });

    const dataStr = JSON.stringify(exportData, null, 2);
    const dataUri = 'data:application/json;charset=utf-8,'+ encodeURIComponent(dataStr);
    
    const link = document.createElement('a');
    link.download = `Timetable_Data_${new Date().toISOString().split('T')[0]}.json`;
    link.href = dataUri;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    
    showNotification('JSON data exported successfully!', 'success');
}

// Export as CSV
function exportCSV() {
    closeExportModal();
    
    let csvContent = "Subject,Code,Faculty,Location,Time Slots\n";
    
    courses.forEach(course => {
        const row = [
            `"${course.name}"`,
            course.code !== 'N/A' ? `"${course.code}"` : '""',
            course.faculty !== 'Not specified' ? `"${course.faculty}"` : '""',
            `"${course.location}"`,
            `"${course.slots.join(', ')}"`
        ].join(',');
        csvContent += row + "\n";
    });
    
    csvContent += "\n\nTimetable Details:\n";
    csvContent += "Day,Slot,Time,Subject,Location\n";
    
    const timeMapping = {
        'A11': '8:30-10:00', 'B11': '10:05-11:35', 'C11': '11:40-13:10',
        'A21': '13:15-14:45', 'A14': '14:50-16:20', 'B21': '16:25-17:55', 'C21': '18:00-19:30',
        'D11': '8:30-10:00', 'E11': '10:05-11:35', 'F11': '11:40-13:10',
        'D21': '13:15-14:45', 'E14': '14:50-16:20', 'E21': '16:25-17:55', 'F21': '18:00-19:30',
        'A12': '8:30-10:00', 'B12': '10:05-11:35', 'C12': '11:40-13:10',
        'A22': '13:15-14:45', 'B14': '14:50-16:20', 'B22': '16:25-17:55', 'A24': '18:00-19:30',
        'D12': '8:30-10:00', 'E12': '10:05-11:35', 'F12': '11:40-13:10',
        'D22': '13:15-14:45', 'F14': '14:50-16:20', 'E22': '16:25-17:55', 'F22': '18:00-19:30',
        'A13': '8:30-10:00', 'B13': '10:05-11:35', 'C13': '11:40-13:10',
        'A23': '13:15-14:45', 'C14': '14:50-16:20', 'B23': '16:25-17:55', 'B24': '18:00-19:30',
        'D13': '8:30-10:00', 'E13': '10:05-11:35', 'F13': '11:40-13:10',
        'D23': '13:15-14:45', 'D14': '14:50-16:20', 'D24': '16:25-17:55', 'E23': '18:00-19:30'
    };
    
    days.forEach(day => {
        timetableSlots[day].forEach(slotId => {
            const course = courses.find(c => c.slots.includes(slotId));
            if (course) {
                const time = timeMapping[slotId] || 'Lunch Break';
                const row = [
                    day,
                    slotId,
                    time,
                    `"${course.name}"`,
                    `"${course.location}"`
                ].join(',');
                csvContent += row + "\n";
            }
        });
    });
    
    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
    const link = document.createElement('a');
    link.href = URL.createObjectURL(blob);
    link.download = `Timetable_${new Date().toISOString().split('T')[0]}.csv`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    
    showNotification('CSV file exported successfully!', 'success');
}

// Print function
function printTimetable() {
    const originalContent = document.body.innerHTML;
    const printContent = document.querySelector('.container').innerHTML;
    
    document.body.innerHTML = `
        <!DOCTYPE html>
        <html>
        <head>
            <title>Smart FFCS Timetable - Print</title>
            <style>
                body { font-family: Arial, sans-serif; margin: 20px; }
                .timetable-container { border: 2px solid #003366; }
                table { width: 100%; border-collapse: collapse; }
                th, td { border: 1px solid #ddd; padding: 8px; text-align: center; }
                th { background-color: #003366; color: white; }
                .course-slot { padding: 5px; border-radius: 4px; margin: 2px; }
            </style>
        </head>
        <body>
            <h1 style="color: #003366; text-align: center;">Smart FFCS Timetable</h1>
            <h3 style="text-align: center;">VIT Bhopal University</h3>
            <div>${printContent}</div>
            <div style="margin-top: 20px; text-align: center; font-size: 12px; color: #666;">
                Generated on ${new Date().toLocaleString()}
            </div>
        </body>
        </html>
    `;
    
    window.print();
    document.body.innerHTML = originalContent;
    location.reload();
}

// Update the old exportTimetable function
function exportTimetable() {
    showExportModal();
}

// Close modal when clicking outside
document.getElementById('exportModal').addEventListener('click', function(e) {
    if (e.target === this) {
        closeExportModal();
    }
});

// Keyboard shortcut for export
document.addEventListener('keydown', function(e) {
    if ((e.ctrlKey || e.metaKey) && e.key === 'e') {
        e.preventDefault();
        showExportModal();
    }
});